- app/assets/sass/application.scss
- app/views/_includes/back-link.njk
- app/views/_includes/breadcrumbs.njk
- app/views/_includes/language-toggle.njk
- app/views/_includes/phase-banner.njk
- app/views/index.html
- app/views/layouts/_base.html
- app/views/ur-r1/repay/letter.html
- app/views/ur-r1/repay/start.html
- set up the index page for navigation
- create the letter and start page
> Start scenario screens

- app/views/ur-r1/repay/start.html
- remove aside from repay start page to align with gov.uk start page
> Update repay start page and remove aside

- app/views/index.html
- app/views/ur-r1/repay/account-summary.html
- app/views/ur-r1/repay/letter.html
- update contact letter to reflect content designers suggestions
> Update contact letter

- app/views/ur-r1/dth/transition-v3-p2.html
- update the button label for v3 transition page
> Update v3 transtion page

- app/views/ur-r1/dth/transition.html
- update transition page to change 'You will' to 'You'll'
> Update v1 transition page

- app/views/layouts/_base-one-login-service-header.html
- app/views/ur-r1/repay/account-summary.html
- package-lock.json
- package.json
- update repay service header with GOV.UK One Login header
> Update repay service header with OL

- app/views/ur-r1/dth/transition-v2.html
- app/views/ur-r1/dth/transition-v3-p2.html
> Update transition pages

- app/views/ur-r1/dth/transition-v2.html
- app/views/ur-r1/dth/transition.html
- updates to transition screens
> Update transition screens

- app/views/dev-ready/email-filter-for-ol/email-address.html
- app/views/index.html
- created a rev ready area for devs to look at ready files
- created the email address page and amended fields for accessibility
> Create dev ready email address page

- app/views/dev-ready/email-filter-for-ol/email-address.html
- app/views/dev-ready/email-filter-for-ol/email-code.html
- app/views/dev-ready/email-filter-for-ol/resend-email.html
- app/views/layouts/_base-dev-ready.html
- created dev ready file for email code and resend email
- updated footer links to match OIDV footer links
> Create dev ready file – email code and resend email

- app/data/session-data-defaults.js
- app/views/dev-ready/experiments/email-linting/linted-email-address.html
- app/views/index.html
- app/views/ur-r1/gds/check-your-email.html
- app/views/ur-r1/gds/sign-in-or-create.html
- create the page for showing users email address they have entered previously
> Experiment email linting

- app/views/index.html
created dev ready files for:
- check your email
- send me a new email
> Create dev ready pages

- app/views/index.html
- app/views/ur-r2/gds/create-password.html
- app/views/ur-r2/gds/returning/return-email-address.html
- app/views/ur-r2/gds/returning/returning-check-your-phone.html
- app/views/ur-r2/gds/returning/returning-enter-password.html
- app/views/ur-r2/gds/returning/returning-prove-your-identity.html
- app/views/ur-r2/gds/returning/returning-you-have-already-proved-your-identity.html
- app/views/ur-r2/gds/sign-in-or-create.html
> Update path D

- app/assets/sass/_panel.scss
- app/assets/sass/application.scss
- app/views/experiments/interruption-card/transition.html
- app/views/ur-r1/dth/transition-v2.html
> Add interruption card

- app/views/index.html
- app/views/ur-r2/gds/notification-account-created-email.html
- created an email notification page
> Create email notification

- app/views/ur-r2/gds/notification-account-created-email.html
- change the url link on email to point user to prototype sign in or create GDS page
> Update email notification

- app/views/ur-r2/gds/account-not-found.html
- app/views/ur-r2/gds/returning/return-email-address.html
- created a routing page to divert non OL users from continuing in the journey
> Route non OL users to error page

- app/views/ur-r2/gds/account-not-found.html
- update button label to reflect GDS button label
> Update button label on page not found

- app/views/ur-r2/gds/check-your-email.html
- replaced the id to show email address
> Update check your email

- app/views/ur-r2/gds/account-not-found.html
- update content on no account found page to match the content in integration site
> Content changes in no email id found

- app/views/index.html
- app/views/layouts/_base-one-login.html
- app/views/ur-r2/gds/account-created.html
- app/views/ur-r2/gds/account-not-found.html
- app/views/ur-r2/gds/check-your-email.html
- app/views/ur-r2/gds/check-your-phone.html
- app/views/ur-r2/gds/choose-how-to-get-security-codes.html
- app/views/ur-r2/gds/create-password.html
- app/views/ur-r2/gds/email-address.html
- app/views/ur-r2/gds/enter-your-mobile-phone-number.html
- app/views/ur-r2/gds/notification-account-created-email.html
- app/views/ur-r2/gds/returning/return-email-address.html
- app/views/ur-r2/gds/returning/returning-check-your-phone.html
- app/views/ur-r2/gds/returning/returning-enter-password.html
- app/views/ur-r2/gds/returning/returning-prove-your-identity.html
- app/views/ur-r2/gds/returning/returning-you-have-already-proved-your-identity.html
- app/views/ur-r2/gds/sign-in-or-create.html
- update footer links to follow GDS routes and create accessibility link on DTH screens
> Update footer links

- app/views/ur-r2/gds/no-one-login/account-not-found.html
- app/views/ur-r2/gds/no-one-login/check-your-email.html
- app/views/ur-r2/gds/returning/return-email-address.html
- created a folder to host the pages required if no one login is found
- created a copy of the check your email page to hold the data so that next time when user come to sign in, we can navigate them to enter password page
- this should solve the issue of users seeing no one login found after creating an account
> Fix no one login found

- app/views/ur-r2/gds/resting-page.html
- changed the url on the link to set Repay start page
> Change href for resting page

- app/routes.js
- app/views/ur-r2/gds/check-your-email.html
- app/views/ur-r2/gds/email-address.html
- package-lock.json
- package.json
- add notify email option to prototype
> Add Notify email

- app/routes.js
- removed notify as it was causing an issue with page loading resulting in Heroku failing page loading
> Remove notify

- app/views/ur-r2/gds/email-address.html
- fixed email address collection routes page
> Fix email address routes

- app/views/index.html
- app/views/ur-r1/gds/sign-in-or-create.html
- app/views/ur-r2/repay/service-agnostic-start.html
- added a service agnostic start page for ur round 3
> Add service agnostic start page

- app/views/ur-r2/gds/resting-page.html
- changed the url to the new start page after Path A
> Fix routing

- app/views/index.html
- app/views/ur-r2/select-a-service.html
- added a services page at the beginning of prototype to let users select a service
> Add services page at start

- app/views/accessibility-statement.html
- app/views/layouts/_base.html
Add Accessibility Statement page to views folder with back link
> Add Accessibility Statement

- app/views/index.html
- app/views/ur-r2/index.html
- app/views/ur-r4/gds/resting-page.html
> Update the kit

- app/views/dev-ready/transition/sign-in-with-govuk-one-login.html
- app/views/index.html
- package-lock.json
- package.json
- created dev ready file for transition page 1
> Create dev-ready transition page

- app/views/dev-ready/transition/sign-in-with-govuk-one-login.html
> Update transition page

- app/views/index.html
- app/views/ur-r4/access/access-to-work-start.html
- app/views/ur-r4/gds/resting-page.html
- created the start page for A2W for path C testing
> Create A2W transition page

- app/views/ur-r4/access/access-to-work-start.html
- updated the start page to include one login sign in information
> Update start page

- app/views/ur-r4/dth/check-your-phone.html
- app/views/ur-r4/dth/sign-in.html
- app/views/ur-r4/gds/notification-account-created-email-alt.html
- app/views/ur-r4/gds/returning/return-email-address.html
* Amended UR4 journey slightly to support returning users that tried to sign in without creating a OL credential. There was an issue where the users email address wasn't being copied over if they went down that unhappy path.
* At the request of our researchers Anja and James, I've created an alternative notification email that bridges Path C and D.
> Minor changes to the UR4 journey

- app/views/ur-r5/access/account-home-page.html
- app/views/ur-r5/dth/transition2.html
- app/views/ur-r5/gds/notification-account-created-email.html
> Update new end points

- app/views/ur-r5/gds/sign-in-or-create.html
> Update GDS start page

- app/views/index.html
- app/views/ur-r5/dth/transition2-v2.html
- added an alternative version of TP2
> Add TP2 alternative

- app/views/index.html
- app/views/ur-r5/access/account-home-page.html
- removed unwanted links from atw homepage header
> Update header navigation

- app/views/ur-r5/gds/sign-in-or-create.html
- updated OL start page inset text
> Update OL start page

- app/views/dev-ready/transition/sign-in-with-govuk-one-login.html
Updating the first transition page in the prototype to the latest content.
> Update first Transition page to dev ready

- app/views/accessibility-statement.html
Amended statement to reflect scope of the two pages in this journey. Statement will be subject to testing outcomes but we don't foresee any issues.
> Update to the Accessibility Statement

- app/views/accessibility-statement.html
New paragraph content for accessibility statement introduction.
> Update to accessibility statement intro paragraph

- app/views/dev-ready/error/technical.html
- app/views/dev-ready/error/timeout-and-bookmark-with-button.html
- app/views/dev-ready/error/timeout-and-bookmark.html
- app/views/index.html
- added technical and timeout/bookmark error pages
> Add error pages

- app/views/footer/accessibility-statement.html
1. Changed 'most' wording to 'all' on 'Using this service' section.
2. Added in non-compliance for the Timing Adjustable criterion
> Updates to the accessibility statement

- app/routes.js
- app/views/idv/computer-or-tablet.html
- app/views/idv/do-you-have-a-smartphone.html
- app/views/idv/filter-question.html
- app/views/idv/kbv-another-way.html
- app/views/idv/proved-identity.html
- app/views/idv/web/address/check-your-address.html
- app/views/idv/web/address/choose-your-address.html
- app/views/idv/web/address/confirm-your-address.html
- app/views/idv/web/address/find-current-address.html
- app/views/idv/web/continue-proving-your-identity-online.html
- app/views/idv/web/driving-licence/enter-dva-driving-licence-details.html
- app/views/idv/web/driving-licence/enter-dvla-driving-licence-details.html
- app/views/idv/web/driving-licence/who-issued-licence.html
- app/views/idv/web/fraud-check.html
- app/views/idv/web/kbv/date-account-opened.html
- app/views/idv/web/kbv/kbv-abandon.html
- app/views/idv/web/kbv/mortgage-balance.html
- app/views/idv/web/kbv/mortgage-payments.html
- app/views/idv/web/kbv/start.html
- app/views/idv/web/kbv/started-phone-contract.html
- app/views/index.html
- created the web routes to IDV
> Create Web IDV routes

- app/routes.js
- app/views/choose-journey.html
- app/views/index.html
- app/views/ur-r5/index.html
- created a new page that filters out the journey
> Create new index

- app/routes.js
- app/views/dev-ready/transition/sign-in-with-govuk-one-login.html
- app/views/dev-ready/transition/your-sign-in-details-have-been-updated.html
- app/views/index.html
- app/views/ol-credential-create-and-signin/account-created.html
- app/views/ol-credential-create-and-signin/check-your-email.html
- app/views/ol-credential-create-and-signin/check-your-phone.html
- app/views/ol-credential-create-and-signin/choose-how-to-get-security-codes.html
- app/views/ol-credential-create-and-signin/create-password.html
- app/views/ol-credential-create-and-signin/email-address.html
- app/views/ol-credential-create-and-signin/enter-your-mobile-phone-number.html
- app/views/ol-credential-create-and-signin/no-one-login/account-not-found.html
- app/views/ol-credential-create-and-signin/no-one-login/check-your-email.html
- app/views/ol-credential-create-and-signin/notification-account-created-email.html
- app/views/ol-credential-create-and-signin/pyi/identity-check-completed.html
- app/views/ol-credential-create-and-signin/pyi/prove-your-identity.html
- app/views/ol-credential-create-and-signin/resting-page.html
- app/views/ol-credential-create-and-signin/returning/return-email-address.html
- app/views/ol-credential-create-and-signin/returning/returning-check-your-phone.html
- app/views/ol-credential-create-and-signin/returning/returning-enter-password.html
- app/views/ol-credential-create-and-signin/returning/returning-prove-your-identity.html
- app/views/ol-credential-create-and-signin/returning/returning-you-have-already-proved-your-identity.html
- app/views/ol-credential-create-and-signin/sign-in-or-create.html
- app/views/service-pages-routes/repay/start.html
- app/views/transition/sign-in-with-govuk-one-login.html
- app/views/transition/your-sign-in-details-have-been-updated.html
- added index journey and routes to prove your identity option
> Complete web journey

- app/assets/sass/application.scss
- app/assets/sass/patterns/post-office-start-page.scss
- app/routes.js
- app/views/choose-journey.html
- app/views/idv/f2f-another-way.html
- app/views/idv/send-to-post-office.html
- app/views/idv/web/driving-licence/enter-dvla-driving-licence-details.html
- app/views/idv/web/passport/enter-passport-details.html
- app/views/layouts/_base-one-login.html
- app/views/ol-credential-create-and-signin/no-one-login/account-not-found.html
- app/views/ol-credential-create-and-signin/no-one-login/check-your-email.html
- app/views/ol-credential-create-and-signin/returning/return-email-address.html
- app/views/ol-credential-create-and-signin/returning/returning-check-your-phone.html
- finished routing for different scenarios
> Finish touch ups

- app/views/ol-credential-create-and-signin/sign-in-or-create.html
- amended GDS OL start page to match GDS prototype
> Amend start page

- app/views/ol-credential-create-and-signin/returning/returning-check-your-phone.html
- app/views/return-to-prototype-home.html
- updated path E to have a stopper page before exiting
> Update path E

- app/views/idv/app/document-checking/android/passport/how-to-scan-passport.html
- fixed an issue with passport scanning page link going into 'page not found'
> Fix android passport scan page

- app/routes.js
- app/views/idv/ipv-core/proved-identity.html
- app/views/idv/proved-identity.html
- app/views/service-pages-routes/maternity-allowance/start.html
1. Selecting A or B path now points to a Maternity Allowance start page.
2. /idv/ipv-core/proved-identity page now points back to a specified MA page. Link added to continue button.
> Temporary A/B path change for Maternity Allowance UR

- package-lock.json
- package.json
Updated govuk frontend and notifications-node-client to latest versions.
> Updated front-end and notifications-node-client

- app/routes.js
- app/views/idv/address-cri/no-photo-id/check-current-address.html
- app/views/idv/address-cri/no-photo-id/choose-current-address.html
- app/views/idv/address-cri/no-photo-id/confirm-address.html
- app/views/idv/address-cri/no-photo-id/find-current-address.html
- app/views/idv/bank-account-cri/before-you-continue.html
- app/views/idv/bank-account-cri/check-details.html
- app/views/idv/bank-account-cri/enter-account-details.html
- app/views/idv/bank-account-cri/escape.html
- app/views/idv/find-another-way.html
- app/views/idv/fraud-cri/no-photo-id/fraud-check.html
- app/views/idv/kbv-cri/experian/no-photo-id/cannot-answer-exit.html
- app/views/idv/kbv-cri/experian/no-photo-id/date-account-opened.html
- app/views/idv/kbv-cri/experian/no-photo-id/kbv-abandon.html
- app/views/idv/kbv-cri/experian/no-photo-id/kbv-start.html
- app/views/idv/kbv-cri/experian/no-photo-id/mortgage-balance.html
- app/views/idv/kbv-cri/experian/no-photo-id/mortgage-payments.html
- app/views/idv/kbv-cri/experian/no-photo-id/proved-identity.html
- app/views/idv/kbv-cri/experian/no-photo-id/started-phone-contract.html
- app/views/idv/nino-cri/enter-nino.html
- app/views/idv/nino-cri/escape.html
- app/views/nophotoidv/check-details.html
- app/views/nophotoidv/dob.html
- app/views/nophotoidv/name.html
- app/views/nophotoidv/no-photo-id-escape.html
- app/views/nophotoidv/no-photo-id-triage.html
Implemented the no photo ID journey as per this ticket https://dwpdigital.atlassian.net/browse/IDTR-17629
It will need refinement.
> No photo ID journey

- app/assets/sass/application.scss
- app/views/idv/ipv-core/proved-identity.html
- app/views/layouts/_base-repay.html
- app/views/service-pages-routes/repay/account-home.html
* Fixed Repay header for account home page
* Changed the link from the proved identity page to lead into Repay account home page
> Minor content updates

- app/routes.js
- app/views/idv/address-cri/repeat-fraud-check/find-current-address.html
- app/views/idv/ipv-core/continuity-of-identity/name-address-success.html
- app/views/idv/ipv-core/continuity-of-identity/name-success.html
- app/views/idv/ipv-core/continuity-of-identity/update-name-app.html
- app/views/idv/ipv-core/continuity-of-identity/update-name-date-birth.html
- app/views/idv/ipv-core/continuity-of-identity/update-your-details.html
- app/views/leaving-prototype.html
- app/views/ol-credential-create-and-signin/returning/returning-you-have-already-proved-your-identity.html
- package-lock.json
- package.json
OL prototype now allows returning users to update their details if they have changed. I've amended our prototype to include this. The routes might need further refinement.
> Update details journey part 1

- app/assets/javascripts/application.js
- app/routes.js
- app/views/idv/ipv-core/continuity-of-identity/update-your-details.html
Fixed branching as it was breaking due to the checkboxes having the same name. Had to also implement a script to ensure the top options on this specific update-your-details page are mutually exclusive with the bottom option.
> Fixed branching

- app/views/_includes/breadcrumbs.njk
- app/views/_includes/phase-bannerz.njk
- app/views/changelog.html
- app/views/layouts/_base-repay-signout.html
- app/views/service-pages-routes/repay/account-home.html
- app/views/service-pages-routes/repay/ol-signin.html
- app/views/service-pages-routes/repay/start.html
Updated Repay header to what is currently on live
Updated Repay breadcrumbs on start page
> Header update
